## Authors the shared Synty materials as Godot resources.
##
## Run this inside your own Godot project, after copying in the converter's output. The
## converter writes one materials.json per pack and deliberately stops there, so that
## every resource id and uid in the resulting .tres is generated by Godot rather than
## hand-written by an external tool.
##
##     godot --headless --import
##     godot --headless --script res://tools/generate_materials.gd
##
## The import pass is required: textures have to be in Godot's cache before this script
## can load them, otherwise every material comes out untextured. Re-run whenever a
## manifest changes. Models never need reconverting for this.
##
## Materials are written next to their manifest. If the folder is not at res://materials,
## pass its location:
##
##     godot --headless --script res://tools/generate_materials.gd -- --materials res://addons/synty/materials
extends SceneTree

const DEFAULT_MATERIALS_DIR := "res://materials"


func _init() -> void:
	var materials_dir := _materials_dir()
	var packs := _list_packs(materials_dir)
	if packs.is_empty():
		push_error("No pack folder containing materials.json found under %s. "
				% materials_dir + "Copy the converter's materials folder into the project, "
				+ "or pass --materials <res://path>.")
		quit(1)
		return

	var written := 0
	var failed := 0
	var missing: Array[String] = []
	for pack in packs:
		var manifest_path := "%s/%s/materials.json" % [materials_dir, pack]
		var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(manifest_path))
		if typeof(parsed) != TYPE_DICTIONARY or not parsed.has("materials"):
			push_error("Malformed manifest: %s" % manifest_path)
			failed += 1
			continue

		print("%s: %d materials" % [pack, (parsed["materials"] as Array).size()])
		for entry in parsed["materials"]:
			var target := "%s/%s/%s.tres" % [materials_dir, pack, str(entry["name"])]
			var material := _build(entry, missing)
			var error := ResourceSaver.save(material, target)
			if error != OK:
				push_error("Failed to save %s (error %d)" % [target, error])
				failed += 1
			else:
				written += 1

	for path in missing:
		push_warning("Texture not found, material left untextured: %s" % path)
	print("\nWrote %d materials, %d failed, %d missing textures." % [written, failed, missing.size()])
	quit(1 if failed > 0 else 0)


func _build(entry: Dictionary, missing: Array[String]) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.resource_name = str(entry["name"])

	material.albedo_texture = _texture(entry, "albedo_texture", missing)
	if entry.has("albedo_color"):
		var color: Array = entry["albedo_color"]
		material.albedo_color = Color(color[0], color[1], color[2], color[3])

	var emission := _texture(entry, "emission_texture", missing)
	if emission != null or entry.has("emission_color"):
		material.emission_enabled = true
		material.emission_energy_multiplier = float(entry.get("emission_energy", 1.0))
		if emission != null:
			material.emission_texture = emission
			# The map is the whole of the emission, the way Maya treats a file connected
			# over a colour. Multiply against white leaves the map exactly as authored,
			# where the default add operator would lift it by the emission colour.
			material.emission = Color.WHITE
			material.emission_operator = BaseMaterial3D.EMISSION_OP_MULTIPLY
		else:
			var glow: Array = entry["emission_color"]
			material.emission = Color(glow[0], glow[1], glow[2])

	var normal := _texture(entry, "normal_texture", missing)
	if normal != null:
		material.normal_enabled = true
		material.normal_texture = normal
		material.normal_scale = float(entry.get("normal_scale", 1.0))

	material.roughness = float(entry.get("roughness", 1.0))
	material.metallic = float(entry.get("metallic", 0.0))

	match str(entry.get("transparency", "")):
		"alpha":
			material.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		"scissor":
			# Cutout foliage and fences: keeps them writing depth and sorting correctly.
			material.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_SCISSOR
	return material


func _texture(entry: Dictionary, key: String, missing: Array[String]) -> Texture2D:
	## The texture a manifest entry names, or null when the entry names none.
	if not entry.has(key):
		return null
	var path := str(entry[key])
	if not ResourceLoader.exists(path):
		missing.append(path)
		return null
	return load(path)


func _materials_dir() -> String:
	## Defaults to res://materials, or wherever "--materials <path>" points.
	var arguments := OS.get_cmdline_user_args()
	var index := arguments.find("--materials")
	if index != -1 and index + 1 < arguments.size():
		return arguments[index + 1].rstrip("/")
	return DEFAULT_MATERIALS_DIR


func _list_packs(materials_dir: String) -> PackedStringArray:
	var packs := PackedStringArray()
	var root := DirAccess.open(materials_dir)
	if root == null:
		return packs
	for name in root.get_directories():
		if FileAccess.file_exists("%s/%s/materials.json" % [materials_dir, name]):
			packs.append(name)
	return packs
